webtalk_init -webtalk_dir C:/Users/gabri/OneDrive/Desktop/Semester 2 2021/CSSE4010/prac4/prac4.sim/sim_1/behav/xsim/xsim.dir/Method2_Test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  6 14:43:05 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "739d2c18-d701-442a-9b3e-5e52fd3a9b1b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e7c5aa1d51f747f18d1e808f1e95a78c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "150 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14408_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3699876128 -regid "" -xml C:/Users/gabri/OneDrive/Desktop/Semester 2 2021/CSSE4010/prac4/prac4.sim/sim_1/behav/xsim/xsim.dir/Method2_Test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gabri/OneDrive/Desktop/Semester 2 2021/CSSE4010/prac4/prac4.sim/sim_1/behav/xsim/xsim.dir/Method2_Test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gabri/OneDrive/Desktop/Semester 2 2021/CSSE4010/prac4/prac4.sim/sim_1/behav/xsim/xsim.dir/Method2_Test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
